name: shell command

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: echo a string
      run: echo "hello world"
    - name: multiline statments
      run: |
        node -v
        npm -v
    - name: Build & push Docker image
    - uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: davcherian/demo-app/docker pull alpine
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}     
        
